src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use http\Message;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank(
        message: "La date de début de réservation ne peut pas être vide",allowNull: false
    )]
    #[Assert\LessThanOrEqual(
        propertyPath: "date_heur_fin",
        message: "La date de départ doit etre inferieur a la date de fin"
    )]
    #[Assert\GreaterThan(
        value: 'now',
        message: "La date de debut doit etre superieur a la date et heure actuelle"
    )]
    private ?\DateTimeInterface $date_heur_depart = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank(
        message: "La date de fin de réservation ne peut pas être vide",allowNull: false
    )]
    #[Assert\GreaterThanOrEqual(
        propertyPath: "date_heur_depart",
        message: "La date de fin doit etre superieur a la date de debut"
    )]
    #[Assert\GreaterThan(
        value: 'now',
        message: "La date de fin doit etre superieur a la date et heure actuelle"
    )]
    private ?\DateTimeInterface $date_heur_fin = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(onDelete: "CASCADE")]
    #[Assert\NotBlank(
        message: "Vous devez choisir un membre",allowNull: false
    )]
    private ?Membre $membre = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(onDelete: "CASCADE")]
    #[Assert\NotBlank(
        message: "Vous devez choisir un vehicule",allowNull: false
    )]
    private ?Vehicule $vehicule = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateHeurDepart(): ?\DateTimeInterface
    {
        return $this->date_heur_depart;
    }

    public function setDateHeurDepart(?\DateTimeInterface $date_heur_depart): static
    {
        $this->date_heur_depart = $date_heur_depart;

        return $this;
    }

    public function getDateHeurFin(): ?\DateTimeInterface
    {
        return $this->date_heur_fin;
    }

    public function setDateHeurFin(?\DateTimeInterface $date_heur_fin): static
    {
        $this->date_heur_fin = $date_heur_fin;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getMembre(): ?Membre
    {
        return $this->membre;
    }

    public function setMembre(?Membre $membre): static
    {
        $this->membre = $membre;

        return $this;
    }

    public function getVehicule(): ?Vehicule
    {
        return $this->vehicule;
    }

    public function setVehicule(?Vehicule $vehicule): static
    {
        $this->vehicule = $vehicule;

        return $this;
    }
}

src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200)]
    #[Assert\NotBlank(
        message: "Le titre ne peut pas etre vide",allowNull: false
    )]
    #[Assert\Length(
        min : 3,
        max : 200,
        minMessage:"Le titre doit contenir au minimum {{ limit }} caractères",
        maxMessage:"Le titre doit contenir au maximum {{ limit }} caractères",
    )]
    private ?string $titre = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(
        message: "La marque ne peut pas etre vide",allowNull: false
    )]
    #[Assert\Length(
        min : 3,
        max : 50,
        minMessage:"La marque doit contenir au minimum {{ limit }} caractères",
        maxMessage:"La marque doit contenir au maximum {{ limit }} caractères",
    )]
    private ?string $marque = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(
        message: "Le modele ne peut pas etre vide",allowNull: false
    )]
    #[Assert\Length(
        min : 3,
        max : 50,
        minMessage:"Le modele doit contenir au minimum {{ limit }} caractères",
        maxMessage:"Le modele doit contenir au maximum {{ limit }} caractères",
    )]
    private ?string $modele = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(
        message: "La description ne peut pas etre vide",allowNull: false
    )]
    #[Assert\Length(
        min : 3,
        minMessage:"La description doit contenir au minimum {{ limit }} caractères",
    )]
    private ?string $description = null;

    #[ORM\Column(length: 200)]
    #[Assert\NotBlank(
        message: "La photo ne peut pas etre vide",allowNull: false
    )]
    #[Assert\Length(
        min : 3,
        max : 200,
        minMessage:"Le chemin vers la photo doit contenir au minimum {{ limit }} caractères",
        maxMessage:"Le chemin vers la photo doit contenir au maximum {{ limit }} caractères",
    )]
    private ?string $photo = null;

    #[ORM\Column]
    #[Assert\NotBlank(
        message: "Le prix journalier ne peut pas etre vide",allowNull: false
    )]
    private ?int $prix_journalier = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'vehicule', targetEntity: Commande::class)]
    #[ORM\JoinColumn(onDelete: "CASCADE")]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->titre;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(?string $marque): static
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(?string $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(?int $prix_journalier): static
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setVehicule($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getVehicule() === $this) {
                $commande->setVehicule(null);
            }
        }

        return $this;
    }
}

src/Form/ProfilType.php
<?php

namespace App\Form;

use App\Entity\Membre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfilType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('pseudo')
            ->add('mdp')
            ->add('nom')
            ->add('prenom')
            ->add('civilite', ChoiceType::class, [
                'choices' => [
                    'homme' => 'm',
                    'femme' => 'f'
                ]
            ])
            ->add('submit', SubmitType::class, [
                'label' => "Modifier",
                'validate' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Membre::class,
        ]);
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Form\ProfilType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class ProfilController extends EvalAbstractController
{
    #[Route('/profil', name: 'app_profil')]
    public function index(): Response
    {
        if($this->getUser() == null){
            return $this->redirectToRoute('homepage');
        }

        return $this->render('profil/index.html.twig', []);
    }

    #[Route('/profil/information', name: 'app_profil_information')]
    public function information(Request $request, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        if($this->getUser() == null){
            return $this->redirectToRoute('homepage');
        }

        $membre = $this->membreRepository->find($this->getUser()->getId());

        $form = $this->createForm(ProfilType::class, $membre, []);
        $form->handleRequest($request);
        if($form->isSubmitted()){
            if($form->isValid()){
                $membre->setMdp(
                    $userPasswordHasher->hashPassword(
                        $membre,
                        $membre->getMdp()
                    )
                );

                $this->security->login($membre);

                $this->membreRepository->add($membre, true);
                $this->addFlash('success', 'Les informations du compte ont bien été modifiées');
                return $this->redirectToRoute('app_profil');
            }else{
                $this->showErrorFlash($membre);
            }
        }
        return $this->render('profil/information.html.twig', [
            'form' => $form
        ]);
    }

    #[Route('/profil/reservation', name: 'app_profil_reservation')]
    public function reservation(Request $request, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        if($this->getUser() == null){
            return $this->redirectToRoute('homepage');
        }

        $membre = $this->membreRepository->find($this->getUser()->getId());

        $reservationOfUser = $this->commandeRepository->findBy([
            'membre' => $membre,
        ]);

        return $this->render('profil/reservation.html.twig', [
            'commandes' => $reservationOfUser,
        ]);
    }
}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/list.css') }}"/>
{% endblock %}


{% block body %}
    <div class="list_item">
        <h2>Bonjour {{ app.user.prenom }} {{ app.user.prenom }}</h2>
        <a href="{{ path('app_profil_information') }}" class="btn btn-primary menu-profil">Changer vos informations de comptes</a>
        <a href="{{ path('app_profil_reservation') }}" class="btn btn-primary menu-profil">Visualisez vos commandes</a>
    <div class="list_item">
{% endblock %}

templates/profil/information.html.twig
{% extends 'base.html.twig' %}

{% block title %}Information{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/list.css') }}"/>
{% endblock %}


{% block body %}
    <div class="list_item">
        <h1>Information du compte</h1>
        {{ form(form) }}
        <a href="{{ path('app_profil') }}" class="btn btn-secondary btnRetour btnWidth100">Retour au menu profil</a>
    <div class="list_item">
{% endblock %}

templates/profil/reservation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commandes{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/list.css') }}"/>
{% endblock %}

{% block body %}
    <div class="list_item">
        <h1 class="text-center">Toutes vos Commandes</h1>
        {% for commande in commandes %}
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img class="img-fluid rounded-start" src="{{ asset( commande.vehicule.photo ) }}" alt="image voiture">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-3">
                                    <h2 class="card-title">{{ commande.vehicule.titre }}</h2>
                                    <p class="card-text"><strong>Marque :</strong>{{ commande.vehicule.marque }}</p>
                                    <p class="card-text"><strong>Prix journalier :</strong>{{ commande.vehicule.prixJournalier }}€</p>
                                </div>
                                <div class="col-md-6">
                                    <p class="card-text"><strong>Description :</strong>{{ commande.vehicule.description }}</p>
                                </div>
                                <div class="col-md-3">
                                    <p class="card-text"><strong>Date de départ :</strong> {{ commande.dateHeurDepart|date('Y/m/d H:i') }}</p>
                                    <p class="card-text"><strong>Date de retour :</strong> {{ commande.dateHeurFin|date('Y/m/d H:i') }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if commandes is empty %}
            <p>Aucune commande n'a été réalisée avec votre compte.</p>
        {% endif %}
        <a href="{{ path('app_profil') }}" class="btn btn-secondary btnRetour btnWidth100">Retour au menu profil</a>
    </div>
{% endblock %}