src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use http\Message;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank(
        message: "La date de début de réservation ne peut pas être vide",allowNull: false
    )]
    #[Assert\LessThanOrEqual(
        propertyPath: "date_heur_fin",
        message: "La date de départ doit etre inferieur a la date de fin"
    )]
    #[Assert\GreaterThan(
        value: 'now',
        message: "La date de debut doit etre superieur a la date et heure actuelle"
    )]
    private ?\DateTimeInterface $date_heur_depart = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank(
        message: "La date de fin de réservation ne peut pas être vide",allowNull: false
    )]
    #[Assert\GreaterThanOrEqual(
        propertyPath: "date_heur_depart",
        message: "La date de fin doit etre superieur a la date de debut"
    )]
    #[Assert\GreaterThan(
        value: 'now',
        message: "La date de fin doit etre superieur a la date et heure actuelle"
    )]
    private ?\DateTimeInterface $date_heur_fin = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(onDelete: "CASCADE")]
    #[Assert\NotBlank(
        message: "Vous devez choisir un membre",allowNull: false
    )]
    private ?Membre $membre = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(onDelete: "CASCADE")]
    #[Assert\NotBlank(
        message: "Vous devez choisir un vehicule",allowNull: false
    )]
    private ?Vehicule $vehicule = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateHeurDepart(): ?\DateTimeInterface
    {
        return $this->date_heur_depart;
    }

    public function setDateHeurDepart(?\DateTimeInterface $date_heur_depart): static
    {
        $this->date_heur_depart = $date_heur_depart;

        return $this;
    }

    public function getDateHeurFin(): ?\DateTimeInterface
    {
        return $this->date_heur_fin;
    }

    public function setDateHeurFin(?\DateTimeInterface $date_heur_fin): static
    {
        $this->date_heur_fin = $date_heur_fin;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getMembre(): ?Membre
    {
        return $this->membre;
    }

    public function setMembre(?Membre $membre): static
    {
        $this->membre = $membre;

        return $this;
    }

    public function getVehicule(): ?Vehicule
    {
        return $this->vehicule;
    }

    public function setVehicule(?Vehicule $vehicule): static
    {
        $this->vehicule = $vehicule;

        return $this;
    }
}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_heur_depart', DateTimeType::class, [
                'widget' => 'single_text',
            ])
            ->add('date_heur_fin', DateTimeType::class, [
                'widget' => 'single_text',
            ])
            ->add('membre')
            ->add('vehicule')
            ->add('submit', SubmitType::class, [
                'label' => $options['labelSubmit'],
                'validate' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
            'labelSubmit' => null
        ]);
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Form\CommandeType;
use App\Repository\CommandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/commande')]
class CommandeController extends EvalAbstractController
{
    #[Route('/admin', name: 'app_commande_index', methods: ['GET'])]
    public function index(CommandeRepository $commandeRepository): Response
    {
        return $this->render('commande/index.html.twig', [
            'commandes' => $commandeRepository->findAll(),
        ]);
    }

    #[Route('/admin/new', name: 'app_commande_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $commande = new Commande();
        $form = $this->createForm(CommandeType::class, $commande, [
            'labelSubmit' => 'Créer'
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if($form->isValid()) {
                $commande->setDateEnregistrement(new \DateTime('now'));
                $entityManager->persist($commande);
                $entityManager->flush();
                $this->addFlash('success', 'La commande a bien été créée');
                return $this->redirectToRoute('app_commande_index', [], Response::HTTP_SEE_OTHER);
            }else{
                $this->showErrorFlash($commande);
            }
        }

        return $this->render('commande/new.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/admin/{id}/show', name: 'app_commande_show', methods: ['GET'])]
    public function show(Commande $commande): Response
    {
        return $this->render('commande/show.html.twig', [
            'commande' => $commande,
        ]);
    }

    #[Route('/admin/{id}/edit', name: 'app_commande_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commande $commande, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommandeType::class, $commande, [
            'labelSubmit' => 'Modifier'
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if($form->isValid()) {
                $entityManager->flush();
                $this->addFlash('success', 'La commande a bien été modifiée');
                return $this->redirectToRoute('app_commande_index', [], Response::HTTP_SEE_OTHER);
            }else{
                $this->showErrorFlash($commande);
            }
        }

        return $this->render('commande/edit.html.twig', [
            'commande' => $commande,
            'form' => $form,
        ]);
    }

    #[Route('/admin/{id}', name: 'app_commande_delete', methods: ['POST'])]
    public function delete(Request $request, Commande $commande, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commande->getId(), $request->request->get('_token'))) {
            $entityManager->remove($commande);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_commande_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commande/_delete_form.html.twig
<form method="post" action="{{ path('app_commande_delete', {'id': commande.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/commande/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/commande/edit.html.twig
{% extends 'back.html.twig' %}

{% block title %}Modifier Commande{% endblock %}

{% block bodyback %}
    <h1>Modifier Commande</h1>

    {{ include('commande/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_commande_index') }}" class="btn btn-secondary btnRetour">Retour a la liste</a>

    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}

templates/commande/index.html.twig
{% extends 'back.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/scipt.js') }}"></script>
{% endblock %}

{% block bodyback %}
    <h1>Commande index</h1>

    <table class="table table-striped" id="myTable">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_heur_depart</th>
                <th>Date_heur_fin</th>
                <th>Date_enregistrement</th>
                <th>Membre</th>
                <th>Vehicule</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.dateHeurDepart ? commande.dateHeurDepart|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.dateHeurFin ? commande.dateHeurFin|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.dateEnregistrement ? commande.dateEnregistrement|date('Y-m-d H:i:s') : '' }}</td>
                <td><a href="{{ path('app_membre_edit', {'id': commande.membre.id}) }}">{{ commande.membre }}</a></td>
                <td><a href="{{ path('app_vehicule_index', {'id': commande.vehicule.id}) }}">{{ commande.vehicule }}</a></td>
                <td>
                    <a href="{{ path('app_commande_show', {'id': commande.id}) }}" class="btn btn-info">Voire</a>
                    <a href="{{ path('app_commande_edit', {'id': commande.id}) }}" class="btn btn-warning">Modifier</a>
                    {{ include('commande/_delete_form.html.twig') }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_commande_new') }}" class="btn btn-success">Créer</a>
{% endblock %}

templates/commande/new.html.twig
{% extends 'back.html.twig' %}

{% block title %}New Commande{% endblock %}

{% block bodyback %}
    <h1>Créer Commande</h1>

    {{ include('commande/_form.html.twig') }}

    <a href="{{ path('app_commande_index') }}" class="btn btn-secondary btnRetour">Retour a la liste</a>
{% endblock %}

templates/commande/show.html.twig
{% extends 'back.html.twig' %}

{% block title %}Commande{% endblock %}

{% block bodyback %}
    <h1>Commande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commande.id }}</td>
            </tr>
            <tr>
                <th>Date_heur_depart</th>
                <td>{{ commande.dateHeurDepart ? commande.dateHeurDepart|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_heur_fin</th>
                <td>{{ commande.dateHeurFin ? commande.dateHeurFin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_enregistrement</th>
                <td>{{ commande.dateEnregistrement ? commande.dateEnregistrement|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Membre</th>
                <td><a href="{{ path('app_membre_edit', {'id': commande.membre.id}) }}">{{ commande.membre }}</a></td>
            </tr>
            <tr>
                <th>Véhicule</th>
                <td><a href="{{ path('app_vehicule_index', {'id': commande.vehicule.id}) }}">{{ commande.vehicule }}</a></td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_commande_index') }}" class="btn btn-secondary btnRetour">Retour a la liste</a>
    <br>
    <a href="{{ path('app_commande_edit', {'id': commande.id}) }}" class="btn btn-warning btnModif">Modifier</a>

    {{ include('commande/_delete_form.html.twig') }}
{% endblock %}